version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: trace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/data/mysql
#
#  springboot-app:
#    build: .
#    container_name: oms-container
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trace
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#
#volumes:
#  mysql-data:
