spring:
  application:
    name:order-processing-service:
  datasource:
    url: jdbc:mysql://localhost:3306/trace
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update